### ISSUE TITLE
OTP HTML Email UI Template

### ISSUE THREAD

**Issue by matxnation** [matxnation/HTML-Emails-UI#1]

**Comment by sirrotich** [comment]
Done the UI design , find attached to the screenshots :
<img width="1235" alt="Screenshot 2024-12-11 at 16 53 58" src="https://github.com/user-attachments/assets/852b488d-344d-4428-a6bb-682cdbb8fc4b" />
<img width="949" alt="Screenshot 2024-12-11 at 16 54 09" src="https://github.com/user-attachments/assets/fb970d66-98c8-46ee-b48f-488faa67fbb7" />

**Comment by sirrotich** [comment]
fixed the bg color

**Comment by matxnation** [comment]
1. Replace the SVG logo with an image link
2. On the Body tag replace "margin-top: 150px;" with "padding-top: 50px;"
![Screenshot_with padding-top-50px](https://github.com/user-attachments/assets/03dbc7d4-19c2-4d95-a610-4a171d814cdb)
![Screenshot_with margin-top-150px](https://github.com/user-attachments/assets/29e1dc2c-fc6d-4b7e-9be5-79144c8e3e30)

**Comment by sirrotich** [comment]
Added the image, altough its coming in a bit blur, check

**Comment by matxnation** [comment]
PNG dimension are 112 × 31
